const projectsData = {
  projects: [
    {
      id: 1,
      img: "images/tictactoe.png",
      heading: "Game : Tic Tac Toe",
      description:
        "The classic game, tic tac toe with a modern and bright look. This started out as a tutorial on React and i expanded it from there.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: true,
      showRouter: false,
      showThree: false,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/react-tictactoe",
      liveLink: "https://kristian-kodehode.github.io/react-tictactoe/",
    },
    {
      id: 2,
      img: "images/Donut-color.png",
      heading: "App : HEX Generator",
      description:
        "Generate and store wonderful colors in HEX code by rotating this donut. A fun and original concept.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: true,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/color-donut",
      liveLink:
        "https://64cfa4a4be3d0c49430eb478--rad-gumdrop-b595c7.netlify.app/",
    },
    {
      id: 3,
      img: "images/calculator-react.png",
      heading: "App : Calculator",
      description:
        "Project task given over the summer to create a functional calculator in React. I do like a challenge, and this was one of them.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: true,
      showRouter: false,
      showThree: false,
      showFigma: true,
      githubLink: "https://github.com/Kristian-kodehode/calculator-v3",
      liveLink: "https://kristian-kodehode.github.io/calculator-v3/",
    },
    {
      id: 4,
      img: "images/stopwatch.png",
      heading: "App : Stopwatch",
      description:
        "Yet another classic project, the stopwatch. For the style concious person that loves to even have the stopwatch look good.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/02_Stopwatch",
      liveLink: "https://kristian-kodehode.github.io/02_Stopwatch/",
    },
    {
      id: 5,
      img: "images/qrgenerator.png",
      heading: "App : QR Generator",
      description:
        "Fun little app that generates QR code from URLs. First time using an API which was a lot of fun.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: true,
      githubLink: "https://github.com/Kristian-kodehode/04_QRCodeGenerator",
      liveLink: "https://kristian-kodehode.github.io/04_QRCodeGenerator/",
    },
    {
      id: 6,
      img: "images/saturnproject.png",
      heading: "Design : Saturn",
      description:
        "Group project with Mohammad in class. Task: to create a site about Saturn. Great experience and collaboration. Html and Css only.",
      showHtml: true,
      showCss: true,
      showJs: false,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: true,
      githubLink:
        "https://github.com/Kristian-kodehode/005-Gruppeprosjekt-Saturn-Mokhammad-Kristian",
      liveLink:
        "https://kristian-kodehode.github.io/005-Gruppeprosjekt-Saturn-Mokhammad-Kristian/",
    },
    {
      id: 7,
      img: "images/startjourney.png",
      heading: "Design : Sign Up Form",
      description:
        "This was one of our first tasks to do something in HTML and CSS. I decided to make a simple Sign Up Form. ",
      showHtml: true,
      showCss: true,
      showJs: false,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: true,
      githubLink: "https://github.com/Kristian-kodehode/003-signUp-page",
      liveLink: "https://kristian-kodehode.github.io/003-signUp-page/",
    },
  ],
};

export { projectsData };
