const projectsData = {
  projects: [
    {
      id: 1,
      img: "images/tictactoe.png",
      heading: "Game : Tic Tac Toe",
      description:
        "The classic game, tic tac toe with a modern and bright look. This started out as a tutorial on React and i expanded it from there.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: true,
      showRouter: false,
      showThree: true,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/react-tictactoe",
      liveLink: "https://kristian-kodehode.github.io/react-tictactoe/",
    },
    {
      id: 2,
      img: "images/snake.png",
      heading: "Game : Snake",
      description:
        "The classic game, Snake with a modern look. This started out as a tutorial and i expanded it quite alot from there.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/game-snake",
      liveLink: "https://kristian-kodehode.github.io/game-snake/",
    },
    {
      id: 3,
      img: "images/Donut-color.png",
      heading: "App : Donut Color",
      description:
        "Generate and store wonderful colors in HEX code by rotating this donut. A fun and original concept.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: true,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/color-donut",
      liveLink:
        "https://64cfa4a4be3d0c49430eb478--rad-gumdrop-b595c7.netlify.app/",
    },
    {
      id: 4,
      img: "images/calculator-react.png",
      heading: "App : Calculator",
      description:
        "Project task given over the summer to create a functional calculator in React. I do like a challenge, and this was one of them.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: true,
      showRouter: false,
      showThree: false,
      showFigma: true,
      githubLink: "https://github.com/Kristian-kodehode/calculator-v3",
      liveLink: "https://kristian-kodehode.github.io/calculator-v3/",
    },
    {
      id: 5,
      img: "images/stopwatch.png",
      heading: "App : Stopwatch",
      description:
        "Yet another classic project, the stopwatch. For the style concious person that loves to even have the stopwatch look good.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/02_Stopwatch",
      liveLink: "https://kristian-kodehode.github.io/02_Stopwatch/",
    },
    {
      id: 6,
      img: "images/IncrediBuy.jpg",
      heading: "Design : Incredibuy",
      description:
        "Yet another classic project, the stopwatch. For the style concious person that loves to even have the stopwatch look good.",
      showHtml: true,
      showCss: true,
      showJs: false,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: true,
      githubLink: "",
      liveLink: "https://kristian-kodehode.github.io/02_Stopwatch/",
    },
    {
      id: 7,
      img: "images/ChillixHome.jpg",
      heading: "Design : Chillix",
      description:
        "Design project where the assignment was to create a fictional streaming service. Should work as a sample, not 100% full prototype.",
      showHtml: false,
      showCss: false,
      showJs: false,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: true,
      githubLink: "",
      liveLink:
        "https://www.figma.com/proto/eLdqwlfPTyqh226WpXQGSw/CHILLIX-STREAMING?page-id=53%3A268&type=design&node-id=74-935&viewport=399%2C398%2C0.04&t=3Avu3zdnJIK0LFrB-1&scaling=scale-down&starting-point-node-id=74%3A935&mode=design",
    },
    {
      id: 8,
      img: "images/routertutorial.png",
      heading: "Tutorial : Router",
      description:
        "I like to do the tutorials from the different libraries, and Router was a good challenge to follow along to and get to work 100%.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: true,
      showRouter: true,
      showThree: false,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/router-tutorial",
      liveLink: "https://kristian-kodehode.github.io/router-tutorial/",
    },
  ],
};

export { projectsData };
