const projectsData = {
  projects: [
    {
      id: 0,
      img: "images/solcellekart2.webp",
      heading: "Saas : Solcellekart (2024)",
      description:
        "Hjelper deg å finne riktig solcelleløsning til ditt tak. Dette var et av mine hovedansvar i min forrige stilling som frontend utvikler og ux.",
      showHtml: false,
      showCss: false,
      showJs: true,
      showReact: true,
      showRouter: true,
      showThree: false,
      showFigma: true,
      liveLink: "https://solcellekart.solintegra.no/",
    },
    {
      id: 1,
      img: "images/ecomshop.webp",
      heading: "Nettbutikk : Shoppi (2023)",
      description:
        "En enkel og fiksjonell e-handelsnettbutikk laget i React + React Router. Data kommer fra fakestore api. Begynner-prosjekt.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: true,
      showRouter: true,
      showThree: false,
      showFigma: true,
      githubLink: "https://github.com/Kristian-kodehode/ecommerce-userflow",
      liveLink: "https://kristian-kodehode.github.io/ecommerce-userflow/",
    },
    {
      id: 2,
      img: "images/Donut-color.png",
      heading: "App : HEX Generator (2023)",
      description:
        "En kreativ og intuitiv måte å generere fargekoder. Ved bruk av three.js kan du rotere denne 3D donuten og finne dine farger.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: true,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/color-donut",
      liveLink: "https://my-hex-generator.netlify.app/",
    },
    {
      id: 3,
      img: "images/tictactoe.png",
      heading: "Spill : Tic Tac Toe (2023)",
      description:
        "Det klassiske spillet Tic Tac Toe laget i React. Et perfekt intro prosjekt til React som viser litt hva React har å by på.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: true,
      showRouter: false,
      showThree: false,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/react-tictactoe",
      liveLink: "https://kristian-kodehode.github.io/react-tictactoe/",
    },
    {
      id: 4,
      img: "images/stopwatch.png",
      heading: "App : Stoppeklokke (2023)",
      description:
        "Javascript prosjekt hvor jeg fokuserte på å lære the basics av javascript, DOM manipulasjon og eksperimentere ned stil i CSS.",
      showHtml: true,
      showCss: true,
      showJs: true,
      showReact: false,
      showRouter: false,
      showThree: false,
      showFigma: false,
      githubLink: "https://github.com/Kristian-kodehode/02_Stopwatch",
      liveLink: "https://kristian-kodehode.github.io/02_Stopwatch/",
    },
  ],
};

export { projectsData };
